### ISSUE TITLE
Research options for database searching

### ISSUE THREAD

**Issue by jessebl** [whitman-books-online/whitman-books-online#1]
Look into the options that we'll have available to us for performant searching of books in the DB. Fuzzy search would be great, but just find what there is to find.

**Comment by ashleygw** [comment]
Looked into this. Fuzzy search is pretty essential. 
http://www.sqlservercentral.com/articles/Fuzzy+Match/92822/
This article provides a good overview of what approaches I think we should implement, and I've written this before, so I'm confident I could again. Most of the code I've found though is written in a database native scripting language, rather than C++. As our initial approach was to use subprocess and just run this through C++, I am beginning to doubt that would be faster than using something more native to the DB.

**Comment by ashleygw** [comment]
http://ginstrom.com/scribbles/2008/08/10/using-custom-functions-with-sqlalchemy-and-sqlite/

This may be helpful in the future too. Further research indicates this may be slower than C, but not significantly, and there are other advantages gained by not using the subprocess module.
